[package]
name = "GuessingGame"
version = "0.1.0"
authors = ["Tchaikochan <68945247+Tchaikochan@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
